version: '3'
services:
  postgres:
    container_name: postgres-monitoring
    image: postgres:16-alpine3.18
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
    volumes:
      - monitoring:/var/lib/postgresql/data
  app:
    container_name: monitoring-management-system2
    image: monitoring-image-ass3-v2
    build: .
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/monitoring
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456789
    links:
      - postgres

volumes:
  monitoring: